### ISSUE TITLE
Engine stops playing after a few moves

### ISSUE THREAD

**Issue by adch99** [WandererXII/lila#1]
I have tried playing a few games with the computer on Lishogi. Twice out of three games, it has happened that the AI side just doesn't move after the first few moves. This shouldn't take so long for the engine because it's so early in the game. Here's a link: https://lishogi.org/VUCsQVlEwuwn
I don't actually know how to play shogi, just saw someone's username as lidraughts.org on lichess and thought about lishogi. 
Also, the GitHub link in your blog post is wrong. It's misspelt.

**Comment by WandererXII** [comment]
Hello, thank you for reporting the issue, I believe I fixed it now.
The reason, if anyone is interested, was that when someone captured a promoted rook, the rook in some occasions wouldn't get demoted served-side - therefore when the engine wanted to drop the rook it has previously captured, server thought the engine had no rook to drop in hand(it saw promoted rook in hand). Sometimes the engine would give another move after a while, since there is some randomness, but that took a while. This all is resolved now.
Thanks again for taking your time to report this, sorry I didn't see this earlier. Also corrected the link in the blog post.
